#!/bin/bash
#STR= cat ~/.ssh/id_rsa.pub
#ssh -i ~/Key/Test.pem ubuntu@18.184.126.175 touch  1.txt; echo "2" > 1.txt
cd ~/.ssh
touch 123
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDS6Pqy8UHKppevrKTmL3JLbX762B+js1CspQxc7n62TfpjcA/N2SH6LABmhXAH8nReaE/y3cquriX4TlMiolFlOb0q8mDjLCN8GOrZMzr4/lfEF1tTjmvqiE5CfNOkzOs6y062j14zkkMdDDwkivAL3kHf5GZL7bfjpz5dlkWNw+W8VJUJPEq8sskBZGF1Aojc9Br790KNfiweW4KzqzHz2zE5ZemOmvbUVAcT9b8Yh+yVft24vrQ0ZP2YNicgHg0eDgJZT2yLCSIMaLJ1Kh2wJgNgpO4fo06/Qwr/ZmiD4KZcrqRnKpMnHjV/HBPF7lxRK4PQthAH0hWLoZuS42B9 ubuntu@ip-172-31-43-154" >> authorized_keys
sudo apt-get -y install python
echo "11" > 2.txt
