---

- hosts: all
#  user: $user
  sudo: yes
 
  vars:
    jar: /home/jenkins/swarm-client-2.2-jar-with-dependencies.jar
    master: http://18.197.185.224:8080/
    user: Silfarion
    jenpass: *********
    label: "{{ lookup('env','label') }}"
    directory: /var/www/html/
    slave_name: slave-for'{{label}}' 
    jenmode: exclusive

  tasks:
  - name: Install Java
    apt:
      name: default-jre
      state: present

  - name: Create jenkins user
    user: 
      name: jenkins
      password: ''
      state: present
      shell: /bin/bash
      home: /home/jenkins

  - name: Download swarm client
    get_url:
      url: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/2.2/swarm-client-2.2-jar-with-dependencies.jar
      owner: jenkins
      dest: /home/jenkins/
      mode: 0440

  - name: Install the package "apache"
    apt:
      name: apache2
      state: present

  - name: Create workspace dir
    file:
      path: /var/www/html
      state: directory
#      mode: 0600
      owner: jenkins
      group: jenkins

  - name: Run swarm
    command: cd /home/jenkins
    command: java -jar '{{ jar }}' -master '{{master}}' -username '{{user}}' -password '{{jenpass}}' -labels '{{label}}' -fsroot '{{directory}}' -mode '{{jenmode}}' -name "{{slave_name}}"
    become: true
    become_user: jenkins
#setsid sh -c
